In [1]:
import torch
print(torch.__version__)

1.2.0+cu92


In [2]:
torch.cuda.is_available()

True

In [3]:
torch.version.cuda

'9.2.148'

In [4]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [5]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

In [6]:
import torch
import numpy as np

t = torch.Tensor()
type(t)

torch.Tensor

In [7]:
print(t.dtype)
print(t.device)
print(t.layout)
# dtype, device相同的才能相加

torch.float32
cpu
torch.strided


1. Since numpy.ndarray objects are allocated on the CPU, the as_tensor() function must copy the data from the CPU to the GPU when a GPU is being used.
2. The memory sharing of as_tensor() doesn’t work with built-in Python data structures like lists.
3. The as_tensor() call requires developer knowledge of the sharing feature. This is necessary so we don’t inadvertently make an unwanted change in the underlying data without realizing the change impacts multiple objects.
4. The as_tensor() performance improvement will be greater if there are a lot of back and forth operations between numpy.ndarray objects and tensor objects. However, if there is just a single load operation, there shouldn’t be much impact from a performance perspective.

In [8]:
device = torch.device('cuda:0')
device


device(type='cuda', index=0)

In [9]:
data = np.array([1, 2, 3])
type(data)


numpy.ndarray

In [10]:
torch.Tensor(data)
# constructot

tensor([1., 2., 3.])

In [11]:
torch.tensor(data)
# factories

tensor([1, 2, 3])

In [12]:
torch.as_tensor(data)
# factories

tensor([1, 2, 3])

In [13]:
torch.from_numpy(data)
# factories

tensor([1, 2, 3])

In [14]:
torch.eye(2)


tensor([[1., 0.],
        [0., 1.]])

In [15]:
torch.zeros(2,2)


tensor([[0., 0.],
        [0., 0.]])

In [16]:
torch.ones(2,2)


tensor([[1., 1.],
        [1., 1.]])

In [17]:
torch.rand(2,2)


tensor([[0.2578, 0.7308],
        [0.8553, 0.9116]])

In [18]:
o1 = torch.Tensor(data)
o2 = torch.tensor(data)
o3 = torch.as_tensor(data)
o4 = torch.from_numpy(data)

In [19]:
print(o1)
print(o2)
print(o3)
print(o4)

print(o1.dtype)
print(o2.dtype)
print(o3.dtype)
print(o4.dtype)

torch.get_default_dtype()


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])
torch.float32
torch.int64
torch.int64
torch.int64


torch.float32

In [21]:
torch.tensor(np.array([1,2,3]))



tensor([1, 2, 3])

In [22]:
torch.tensor(np.array([1.,2.,3.]))


tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [25]:
data[0]=0
data[1]=1
data[2]=2
# t1,t2 copy data | t3, t4 share data
# tensor(data) 首选
# as_tensor() 其次

In [26]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [27]:
print(t3)
print(t4)

tensor([0, 1, 2])
tensor([0, 1, 2])
